Maths_Project.pdf: Maths_Project.tex Maths_Project.bib
	./latexmk.pl -pdf Maths_Project.tex

Maths_Project_Presentation.pdf: Maths_Project_Presentation.tex
	./latexmk.pl -pdf Maths_Project_Presentation.tex

clean:
	rm *.aux *.bbl *.blg *.fdb_latexmk *.log *.pdf *.toc *.nav *.out *.snm
